In [1]:
import numpy as np
import pandas as pd

In [69]:
df = pd.read_csv('customer.csv')
df.head(6)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes

In [70]:
df = df.iloc[:,2:]

In [71]:
df.head(6)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No
5  Average    School       Yes

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=.2)

In [73]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School','UG','PG']])

In [74]:
X_train.head(6)

review education
21  Average        PG
45     Poor        PG
32  Average        UG
35     Poor    School
20  Average    School
23     Good    School

In [75]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [76]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [82]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [83]:
X_train

array([[1., 2.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [0., 2.]])

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [85]:
y_train

21     No
45    Yes
32    Yes
35    Yes
20    Yes
23     No
8      No
38     No
11    Yes
41    Yes
29    Yes
3      No
16    Yes
6      No
2      No
36    Yes
33    Yes
31    Yes
37    Yes
49     No
42    Yes
39     No
22    Yes
46     No
15     No
44     No
12     No
0      No
13     No
17    Yes
5     Yes
7     Yes
14    Yes
10    Yes
28     No
40     No
18     No
4      No
24    Yes
43     No
Name: purchased, dtype: object

In [86]:
le.fit(y_train)

LabelEncoder()

In [87]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [88]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0])

In [38]:
import numpy as np
import pandas as pd

In [91]:
df = pd.read_csv('customer.csv')
df.head(6)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes

In [40]:
encode = df.iloc[:,2:-1]

In [56]:
df.drop(['review','education'], axis='columns',inplace=True)

In [57]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [58]:
encoder_data = oe.fit_transform(df.iloc[:,2:-1])

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [ ]:
encoder_data

In [46]:
encoder_data = pd.DataFrame(encoder_data, columns=encode.keys())

In [47]:
encoder_data = encoder_data.astype('int32')

In [59]:
df_new = pd.concat([df,encoder_data], axis=1)

In [60]:
df_new.head(6)

age  gender purchased  review  education
0   30  Female        No       1          0
1   68  Female        No       0          1
2   70  Female        No       2          2
3   72  Female        No       2          2
4   16  Female        No       1          1
5   31  Female       Yes       1          0

In [66]:
ohe_data = df.iloc[:,1]

In [68]:
ohe_data = pd.DataFrame(ohe_data)

In [69]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [78]:
ohe_data = ohe.fit_transform(ohe_data)

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [80]:
ohe_data_real = ohe_data.toarray()

In [84]:
df_ohe = pd.DataFrame(ohe_data_real,columns=['Female','Male'])

In [94]:
df_ohe = df_ohe.astype('int32')

In [125]:
df_new2 = pd.concat([df_new,df_ohe], axis=1)

In [126]:
df_new2.drop(['gender'],axis='columns', inplace = True)

In [127]:
df = df_new2

In [129]:
df.head()

age purchased  review  education  Female  Male
0   30        No       1          0       1     0
1   68        No       0          1       1     0
2   70        No       2          2       1     0
3   72        No       2          2       1     0
4   16        No       1          1       1     0

In [130]:
df1 = df.iloc[:,2:]

In [131]:
df2 = pd.DataFrame(df.iloc[:,0])

In [132]:
df3 = pd.DataFrame(df.iloc[:,1])

In [133]:
df = pd.concat([df1,df2,df3], axis=1)

In [136]:
df.sample(5)

review  education  Female  Male  age purchased
8        1          1       1     0   65        No
13       1          0       1     0   57        No
9        2          1       0     1   74       Yes
36       2          1       1     0   34       Yes
25       2          0       1     0   57        No

In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(df.iloc[:,0:5], df.iloc[:,-1])

In [145]:
from sklearn.preprocessing import LabelEncoder
oe = LabelEncoder()

In [146]:
oe.fit_transform(y_train)

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [1]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv('customer.csv')
df.head(6)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=.2)

In [45]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']], dtype=np.int32)

In [46]:
X_train

age  gender   review education
10   98  Female     Good        UG
32   92    Male  Average        UG
39   76    Male     Poor        PG
1    68  Female     Poor        UG
29   83  Female  Average        UG
30   73    Male  Average        UG
25   57  Female     Good    School
16   59    Male     Poor        UG
37   94    Male  Average        PG
38   45  Female     Good    School
40   39    Male     Good    School
36   34  Female     Good        UG
11   74    Male     Good        UG
47   38  Female     Good        PG
3    72  Female     Good        PG
4    16  Female  Average        UG
14   15    Male     Poor        PG
35   74    Male     Poor    School
46   64  Female     Poor        PG
24   16  Female  Average        PG
2    70  Female     Good        PG
20   57  Female  Average    School
17   22  Female     Poor        UG
45   61    Male     Poor        PG
31   22  Female     Poor    School
42   30  Female     Good        PG
18   19    Male     Good    School
43   27    Male     Poor        PG
49   25  Female     Good        UG
12   51    Male     Poor    School
27   69  Female     Poor        PG
9    74    Male     Good        UG
13   57  Female  Average    School
48   39  Female     Good        UG
28   48    Male     Poor    School
7    60  Female     Poor    School
23   96  Female     Good    School
34   86    Male  Average    School
41   23    Male     Good        PG
0    30  Female  Average    School

In [71]:
X_train_encode = oe.fit_transform(X_train[['review','education']])
X_test_encode = oe.transform(X_test[['review','education']])

In [72]:
df_new = np.hstack((X_train[['age','gender']].values, X_train_encode))

In [73]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop=True)

In [74]:
df_real = pd.DataFrame(np.hstack(([df_new, y])))

In [75]:
y = pd.DataFrame(y_train)

In [76]:
df_real.rename(columns={0:'Age',1:'Gender',2:'Review',3:'Education',4:'Purchased'},inplace=True)